apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: todo
  labels: 
    app: todo
    tier: backend
spec:
  selector: 
    matchLabels: 
      app: todo
  replicas: {{ .Values.deployment.workers.replicas }}      
  template: 
    metadata: 
      name: todo
      labels: 
        app: todo
        tier: backend
      annotations:
        jenkins/build: {{ .Values.metadata.jenkins.buildTag | quote }}
        git/commitId: {{ .Values.metadata.git.commitId | quote }}
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: RDS_DB_NAME
              name: todo-web-application-config
        - name: RDS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: RDS_HOSTNAME
              name: todo-web-application-config
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: RDS_PASSWORD
              name: todo-web-application-secrets
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              key: RDS_PORT
              name: todo-web-application-config
        - name: RDS_USERNAME
          valueFrom:
            configMapKeyRef:
              key: RDS_USERNAME
              name: todo-web-application-config
        image: "in28min/todo-web-application-mysql:0.0.1-SNAPSHOT"
        name: todo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
